version: '3'

services:
  postgres:
      image: postgres
      volumes:
        - .docker/dbdata:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      build: .
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      volumes:
        - ./meutema:/opt/jboss/keycloak/themes/meutema
      ports:
        - 8080:8080
      depends_on:
        - postgres

        